### ISSUE TITLE
Rethinking recurrence logic

### ISSUE THREAD

**Issue by Guite** [nutso/redmine-plugin-recurring-tasks#76]
I added a few recurrences and executed the cronjob. This caused all recurrent issues being processed. Shouldn't it only process those items where the next execution date has been reached?

**Comment by nutso** [comment]
It should check each recurring issue to see whether it is due to recur, and if it is due to recur, it will add a recurrence.

What were the settings/values you had for recurrences that you did not expect to see recur but did?

**Comment by Guite** [comment]
Let's take an example: I have an issue with a start date of 2015-05-01, a due date of 2015-05-03 and status closed. The issue has one recurrence defined with a fixed schedule of 1 year.

Now what I would expect is that the next issue is created on 2016-05-01.

At the moment it does the following at https://github.com/nutso/redmine-plugin-recurring-tasks/blob/master/app/models/recurring_task.rb#L225
```
    if fixed_schedule
      previous_date_for_recurrence <= Time.now.to_date # TODO add a day?
```
Whereby `previous_date_for_recurrence` returns the last due date in https://github.com/nutso/redmine-plugin-recurring-tasks/blob/master/app/models/recurring_task.rb#L302

This causes that there will always exist an open issue for all recurrent issues.

I propose changing two aspects here:

1. Use the start date instead of the due date for calculating the next execution date (for fixed schedules).
2. Use the next execution date for comparison to decide whether the next recurrence should be processed or not, instead of the previous due date.

Then the issue would created not today, but on 2016-05-01. So you always will have only those issues open which actually need to be worked on.

**Comment by nutso** [comment]
For the second proposal -- from a planning perspective, there is value to seeing issues that have not started yet as open (e.g. in calendar and gantt views) which is why I create/reopen the issue as soon as it can be recurred. Using filters in Redmine, users should be able to filter out issues that have a future start date, so I think recurring earlier rather than later should allow for the most flexibility. 

For the first proposal -- agree that the start date should not be set to the due date on recurrence. Will probably need to calculate the number of days differential and set the start date to that many days before the due date, i.e. set the due date as it currently is, and subtract the original issue timespan in order to set the new start date.

**Comment by nutso** [comment]
start date implemented for next release
