### ISSUE TITLE
Sort list page by next execution date

### ISSUE THREAD

**Issue by Guite** [nutso/redmine-plugin-recurring-tasks#77]
It would be great if the list of recurrences would (or could) be sorted by the next execution date column.

**Comment by nutso** [comment]
Will be included in the next release (2.0.0). 

I think the various date formats may end up being an issue, but closing the issue and will address date formats if it becomes an issue. Using client-side sorting via jquery.tablesorter since the execution date is a calculated field. Date column sorts in the correct order (i.e. not just alphabetically) out of the box at least for my locale/date format.
